trigger:
  branches:
    include:
      - master  # Trigger the pipeline on changes to the master branch

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu-based virtual machine for the build

steps:
  # Step 1: Set up Python environment
  - task: UsePythonVersion@0  # Specify the major version of the task
    inputs:
      versionSpec: '3.12.3'  # Specify the Python version to use (3.x for the latest)
      addToPath: true

  # Step 2: Install dependencies (Selenium, Pytest, and other required packages)
  - script: |
      python -m pip install --upgrade pip  # Upgrade pip
      pip install -r requirements.txt      # Install dependencies from requirements.txt
    displayName: 'Install dependencies'

  # Step 3: Run Pytest to execute the tests
  - script: |
      pytest tests/End_To_End_Testing/test_TC_001.py  # Adjust to your test directory
    displayName: 'Run Pytest'
  
  # Optional Step: Publish test results (JUnit format)
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'           # Use JUnit for Pytest results
      testResultsFiles: '**/junit*.xml'    # Path to test result files
      failTaskOnFailedTests: true
